# H2 Database (for testing)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Before the study, users are redirected to LimeSurvey pre-questionnaire.
study.limesurvey.pre-url=https://edyta31.limesurvey.net/934711?lang=en&uid=

# After the study, users are redirected to LimeSurvey post-questionnaire.
study.limesurvey.post-url=https://edyta31.limesurvey.net/index.php/YOUR_POST_SURVEY_ID&uid=

study.openai.api-key=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
